name: Kotlin CI

on:
  push:
    branches: [ main ]
    paths: [ kt/** ]
  pull_request:
    branches: [ main ]
    paths: [ kt/** ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/*gradle*') }}
          path: ~/.gradle
      - run: ./gradlew --info check
        working-directory: kt

  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
