name: Python pytest-benchmark

on:
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-inputs
          path: day*.txt
      - name: Get inputs
        run: make
        env:
          SESSION: ${{ secrets.SESSION }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile*') }}
          path: |
            ~/.local/share/virtualenv
            ~/.local/share/virtualenvs
      - run: python -m pip install --upgrade pipenv
      - name: Run pipenv run pytest-benchmark
        run: |
          pipenv install -d
          pipenv run pytest --benchmark-enable --benchmark-only --benchmark-histogram=../docs/benchmark
        working-directory: py
      - uses: EndBug/add-and-commit@v5
        with:
          add: docs
          message: 'Benchmark ${{ github.sha }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
