name: Rust Criterion

on:
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.*') }}
          path: ~/.cargo
      - run: |
          cargo bench --bench criterion -- --verbose
          rsync --archive --delete --verbose --whole-file target/criterion/ ../docs/criterion/
        working-directory: rs
      - uses: EndBug/add-and-commit@v5
        with:
          add: docs
          message: 'Benchmark ${{ github.sha }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
